---
blueprint:
  name: Disable obstacle avoidance on selected room
  description: Disable/Enable obstacle avoidance according to the robots current room
  domain: automation
  source_url: https://github.com/Tasshack/dreame-vacuum/blob/master/blueprints/automation/disable_obstacle_avoidance_on_selected_room.yaml
  input:
    vacuum:
      name: Vacuum
      selector:
        entity:
          domain: vacuum
    segment_id:
      name: Selected room id
      selector:
        number:
          min: 1
          max: 62
          mode: box


mode: single

variables:
  segment_id: !input segment_id
  vacuum: !input vacuum
  vacuum_name: "{{ vacuum.split('.')[1] }}"
  sensor_name: "sensor.{{ vacuum_name }}_current_room"
  switch_name: "switch.{{ vacuum_name }}_obstacle_avoidance"
  camera_name: "camera.{{ vacuum_name }}_map"

trigger:
  - platform: state
    entity_id: "{{ camera_name }}"
    attribute: vacuum_position
condition: |
    {{ 
        (
            states[sensor_name].state != 'unavailable' and 
            (
                (
                    states[switch_name].state == 'on' and 
                    states[sensor_name].attributes.room_id == segment_id
                ) or 
                (
                    states[switch_name].state == 'off'
                )
            )
        ) 
    }}

action:
    - service: | 
        {% if states[sensor_name].attributes.room_id == segment_id %}
            switch.turn_off
        {% else %}  
            switch.turn_on
        {% endif %}
    target:
        entity_id: "{{ switch_name }}"
    data: {}